heroku/heroku-kafka-jsplugin

commands/configure_topic.js
commands/create_topic.js
commands/shared.js
test/index.js

I'm punting on the `extractFlags` duplication. Something like https://github.com/heroku/cli/issues/265 would make this better, but I think moving the function into `shared.js` without something like that would be worse than the duplication, since it's weird to `exit()` there on flag validation (though I'm on the fence; I can move it if you think that's better).

Allow units on retention time

---

commands/configure_topic.js
commands/create_topic.js

* Remove obsolete 'in milliseconds' from relevant options
* Change naming to be more consistent with style guidelines https://devcenter.heroku.com/articles/cli-style-guide?preview=1

Clean up docs

---

commands/upgrade.js

currently our upgrade text says `done` when it's really just `started`
```
Upgrading to version 0.10... done.
Use `heroku kafka:info` to monitor the upgrade.
```
This changes it to document things a bit more clearly.

better text when upgrading clusters

---

commands/create_topic.js
commands/delete_topic.js
commands/fail.js
commands/upgrade.js

https://github.com/heroku/heroku-kafka-jsplugin/commit/0547ffd15c317952f14f150944fbd7aba1c94c7e
removed all the `confirm` from `flags`. These are needed, without them
`--confirm` never works.

fix --confirm

---

README.md

1. Users expect to have installation instructions listed first.
2. If someone wants to contribute, they need to `npm install` before `plugins:link`.

invert readme orders for clarity

---

README.md
commands/info.js
commands/jmx.js
commands/zookeeper.js

(Assumes #79 and #80 are in, so includes those commits)

Hide kafka jmx and kafka zookeeper for now

---

commands/info.js
test/commands/info_test.js

The config var information in kafka:info is based on metadata from the
provider endpoint in the kafka API. However, that may not be there
until a while after the initial provision, during which period the
config vars show up empty (or, prior to the refactor, incorrectly
defaulting to `KAFKA_URL`).
However, the information can instead be fetched from the
`/addon-attachments` Heroku API endpoint. This does not work for
"pseudo-attachments" (i.e., just copying around config vars), but
that's strongly discouraged anyway and we shouldn't support it.

Have kafka:info display config vars from attachments

---

commands/topics_tail.js
commands/topics_write.js
commands/zookeeper.js
lib/shared.js
test/commands/topics_tail_test.js
test/commands/topics_write_test.js
test/commands/zookeeper_test.js
test/lib/shared_test.js

This also fixes the error handling for kafka:write and kafka:tail for private clusters (#84 only fixed part of the problem).
Sorry, I don't know where I got the idea that private plan names started with `private`--I should have checked against the actual plans.

Unify and test private plan check

---

commands/topics_tail.js
commands/topics_write.js
commands/zookeeper.js

New output:
```
maciek@mothra:~/code/aux/heroku-kafka-jsplugin$ heroku help kafka
Usage: heroku kafka [CLUSTER]
display cluster information
-a, --app APP       # app to run command against
-r, --remote REMOTE # git remote of app to run command against
Additional commands, type "heroku help COMMAND" for more details:
...
kafka:topics:tail TOPIC [CLUSTER]                      #  (only outside Private Spaces) tails a topic in Kafka
kafka:topics:write TOPIC MESSAGE [CLUSTER]             #  (only outside Private Spaces) writes a message to a Kafka topic
...
kafka:zookeeper VALUE [CLUSTER]                        #  (Private Spaces only) control direct access to Zookeeper of your Kafka cluster
```
(output for unaffected commands elided)

Add info regarding Private Spaces constraints to relevant commands

---

commands/topics_tail.js
commands/topics_write.js

Turns out there is a way to silence the logging output from `no-kafka`--with this `write` produces no output and `tail` only outputs the messages.
Fixes https://github.com/heroku/herokudata/issues/508

Silence log output from no-kafka

---

commands/info.js
commands/topics.js
commands/topics_compaction.js
commands/topics_create.js
commands/topics_destroy.js
commands/topics_info.js
commands/topics_replication_factor.js
commands/topics_retention_time.js
package.json
test/commands/info_test.js
test/commands/topics_compaction_test.js
test/commands/topics_create_test.js
test/commands/topics_destroy_test.js
test/commands/topics_info_test.js
test/commands/topics_replication_factor_test.js
test/commands/topics_retention_time_test.js
test/commands/topics_test.js

Implements the Kafka cli relying on `/data` apis, to remove duplication of work on the shogun side.
See https://github.com/heroku/shogun/pull/5662 for a prerequisite shogun PR.
Staging
- email thread: https://groups.google.com/a/heroku.com/forum/#!topic/dod-kcz/DJj9kfNQjNg
- trello card: https://trello.com/c/lcgX8ZrW/472-eliminate-client-data-endpoints-mismatches-and-add-tests

use data apis instead of client

---

commands/info.js

The previous approach could lead to under-counting if
__consumer_offsets is not returned from the API for whatever reason.

Explicitly ignore __consumer_offsets, don't just adjust total count

---

commands/info.js
test/commands/info_test.js

Drop duplicate add-on name in kafka:info

---

commands/configure.js
commands/credentials_rotate.js
commands/fail.js
commands/jmx.js
commands/topics.js
commands/topics_compaction.js
commands/topics_create.js
commands/topics_destroy.js
commands/topics_info.js
commands/topics_replication_factor.js
commands/topics_retention_time.js
commands/upgrade.js
commands/zookeeper.js

Due to the authentication mechanism we use, we need to be
pre-authenticated anytime we talk to the heroku-kafka API for anything
that requires 2FA. Because the first call we usually make is to the
Heroku API (to get app info about the cluster(s) we are interacting
with), requiring preauth on the commands works around this issue.
The exceptions here are the `topics:tail` and `topics:write` commands,
which talk to the cluster directly and not to the heroku-kafka API.

Preauth anything that talks to the heroku-kafka API

---

commands/credentials_rotate.js
commands/fail.js
commands/info.js
commands/jmx.js
commands/topics.js
commands/topics_compaction.js
commands/topics_create.js
commands/topics_destroy.js
commands/topics_info.js
commands/topics_replication_factor.js
commands/topics_retention_time.js
commands/upgrade.js
commands/zookeeper.js
lib/clusters.js
test/commands/credentials_rotate_test.js
test/commands/fail_test.js
test/commands/info_test.js
test/commands/jmx_test.js
test/commands/topics_compaction_test.js
test/commands/topics_create_test.js
test/commands/topics_destroy_test.js
test/commands/topics_info_test.js
test/commands/topics_replication_factor_test.js
test/commands/topics_retention_time_test.js
test/commands/topics_tail_test.js
test/commands/topics_test.js
test/commands/topics_write_test.js
test/commands/upgrade_test.js
test/commands/wait_test.js
test/commands/zookeeper_test.js

if we use the name, `heroku addons:rename` breaks the addon lookup until the
control plane has updated it's cached information.
This requires work on the Heroku Kafka backend as well, but this is a
start.

use addon id instead of name

---

commands/credentials_rotate.js
commands/fail.js
commands/jmx.js
commands/upgrade.js
commands/zookeeper.js
lib/clusters.js
test/commands/credentials_rotate_test.js
test/commands/fail_test.js
test/commands/jmx_test.js
test/commands/upgrade_test.js
test/commands/wait_test.js
test/commands/zookeeper_test.js

We're removing the `/client` endpoints entirely, so we need to transfer off them

use /data endpoints instead of /client endpoints

---

commands/topics_create.js
test/commands/topics_create_test.js

We should not set the `default_partitions` for topic creation. We will let the addon plan determine the default_partitions if the user does not explicitly set them on the command line.

do not set default_partitions for topic creation

---

README.md
commands/topics_tail.js
commands/topics_write.js
lib/shared.js
package.json
test/commands/topics_tail_test.js
test/commands/topics_write_test.js

Some users may have prefixed topic names. This commit adds support for prepending the prefix to the topic name when producing and consuming.
Additionally, the `no-kafka` dependency is updated and locked to 3.1.0.

add topic prefix support

---

commands/topics_create.js
test/commands/topics_create_test.js

Technically this is a breaking change, but it would only be breaking for users who pass `--confirm` to `kafka:topics:create` to get around the restriction on not being able to create RF: 1 topics. However, we haven't supported plans that allow RF topics in forever anyway, so this is moot.
Fixes #73.

Drop pointless guard against RF: 1 topics

---

commands/topics_info.js
test/commands/topics_info_test.js

when testing mixed compaction/retention (as of KIP-71), I found that we
don't display retention if compaction is enabled. The data API now
always returns `compaction_enabled` and `retention_enabled` as fields,
so we need to respect those.

mix compaction and retention in topic info

---

commands/info.js
test/commands/info_test.js

some clusters have a max number of topics. If there is one, display it
in the CLI output like so:
```
Topics:    0 / 10 topics, see heroku kafka:topics
```

show max topics limit in heroku kafka:info

---

commands/upgrade.js
test/commands/upgrade_test.js

tell them "we're going to restart nodes" before they actually start that

warn users about upgrades in the confirm text

---

commands/topics.js
test/commands/topics_test.js

if there are topic limits on the addon, show them in `heroku kafka:topics`

show topic limits if they're there in kafka:topics

---

commands/topics_compaction.js
commands/topics_create.js
commands/topics_info.js
commands/topics_replication_factor.js
commands/topics_retention_time.js
lib/clusters.js
lib/shared.js
test/commands/topics_compaction_test.js
test/commands/topics_create_test.js
test/commands/topics_info_test.js
test/commands/topics_replication_factor_test.js
test/commands/topics_retention_time_test.js
test/lib/shared_test.js

This aligns the CLI usage of the PUT `.../topics/:name` endpoint to what @halorgium and I discussed.

Fix kafka:topics:compaction and kafka:topics:retention-time

---

commands/consumer_groups_create.js
test/commands/consumer_groups_create_test.js

this 400 is because kafka consumer group creation doesn't need to happen
on clusters that have enough credentials to use any consumer group. We
don't need to error here
sample output:
```
$ heroku kafka:consumer-groups:create greetings; echo $?
Creating consumer group greetings... done
▸    kafka-REDACTED-36649 does not need consumer groups managed explicitly, so this command does nothing
0
```

catch 400 in kafka consumer group creation

---

commands/configure.js
commands/topics_create.js

CLI v5 only sends the flags the user passed in on the flags object,
but CLI v6 sends in all defined flags, with values of `undefined` for
ones not explicitly set. Since `'a' in { a: undefined }` is true,
change these to use an explicit check against `undefined` instead.
Fixes #159

Avoid using the 'in' operator to check for presence of flags

---

commands/credentials_rotate.js
test/commands/credentials_rotate_test.js

The CLI framework has some quirks around boolean flags, including that
they don't obey the required option (which admittedly is kind of a
weird thing to do; this was originally done for consistency with
Postgres but now Postgres does something different). Work around this
by explicitly checking for the presence of the flag.

Make kafka:credentials --reset flag required

---

.travis.yml
lib/clusters.js
package.json
test/lib/clusters_test.js
yarn.lock

We are planning to make the API's handling of topic prefixes more implicit - if you pass an already prefixed topic, we want to remove it. However, that can't handle all cases. Specifically, altering topic config whilst passing in a prefixed topic name won't work:
```
$ heroku kafka:topics:compaction potomac-28278.messages enable kafka-tcrayford-octagonal-52951
▸    topic potomac-28278.messages not found
```
This is because the filter in https://github.com/heroku/heroku-kafka-jsplugin/blob/master/lib/clusters.js#L74-L77 doesn't handle this case.
Instead, also check against a prefixed name, by concatting the topic's prefix and the raw topic name.

fix for topic prefix removal bug

---

lib/utilizationBar.js
package.json
test/lib/utilizationBar_test.js
yarn.lock

This lets us mock out color handling consistently in tests (cf. the current issue with `yarn release`).

use cli.color instead of using chalk directly

---

commands/topics_tail.js
commands/topics_write.js
lib/shared.js
test/commands/topics_tail_test.js
test/commands/topics_write_test.js
test/lib/shared_test.js

Currently, if the attachment name is lowercase, the config vars
will still be uppercase, and :tail and :write fail in ugly ways.

Revamp config var lookup to make it more robust

---

commands/topics.js
commands/topics_create.js
commands/topics_info.js
test/commands/topics_create_test.js
test/commands/topics_info_test.js
test/commands/topics_test.js

So I coded up what we talked about in https://github.com/heroku/herokudata/issues/870 , but the Dev Center links don't feel right: they take up a disproportionate amount of room. I think we should keep it in topic creation, but drop it in other places and just list the prefix there. Thoughts?
topic creation:
```
maciek@mothra:~/code/heroku-kafka-jsplugin$ h kafka:topics:create foobar -a multitenant-kafka
Creating topic foobar with compaction disabled and retention time 1 day on kafka-encircled-64755... done
Use `heroku kafka:topics:info foobar` to monitor your topic.
Your topic is using the prefix 'colville-77398.'. Learn more in Dev Center:
https://devcenter.heroku.com/articles/multi-tenant-kafka-on-heroku#connecting-kafka-prefix
```
topic listing:
``` …
```

Make the kafka topic prefix more explicit

---

commands/wait.js
test/commands/wait_test.js

Running `heroku kafka:wait COLOR -a sushi` on my app will not honor the attachment name and instead return data on **all** addons. This PR fixes the `cluster` constant so that it does honor that attachment name if provided.

fix casing of cluster constant

---

.coveralls.yaml

This appears to no longer be necessary

Drop obsolete coveralls.yaml

---

.travis.yml
lib/shared.js

* fix `formatIntervalFromMilliseconds` in node 12.
* bump test matrix from node 8 to node 10 and node 12.

fix: interval formatting helper in node 12

---

commands/topics_tail.js
commands/topics_write.js
lib/shared.js
test/commands/topics_tail_test.js
test/commands/topics_write_test.js
test/lib/shared_test.js

New Private & Shield Kafka addons can use `kafka:topics:write` and `kafka:topics:tail`. This PR removes that guard.

feat: remove Private restriction on write/tail

---

commands/topics_tail.js
commands/topics_write.js

Using these commands in Private and Shield clusters is possible if customers allowlist the IP addresses they're connecting from with the mTLS feature.
Updating the help messages of these commands to clarify that.

Clarify Private and Shield access in topics:tail and topics:write commands

---

.github/workflows/tests.yaml
lib/host.js
test/commands/consumer_groups_create_test.js
test/commands/consumer_groups_destroy_test.js
test/commands/consumer_groups_test.js
test/commands/credentials_rotate_test.js
test/commands/fail_test.js
test/commands/host_test.js
test/commands/info_test.js
test/commands/topics_compaction_test.js
test/commands/topics_create_test.js
test/commands/topics_destroy_test.js
test/commands/topics_info_test.js
test/commands/topics_replication_factor_test.js
test/commands/topics_retention_time_test.js
test/commands/topics_test.js
test/commands/upgrade_test.js
test/commands/wait_test.js
test/commands/zookeeper_test.js
test/lib/clusters_test.js
test/lib/utilizationBar_test.js

Gus: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001eh1AJYAY/view

Updates default host to api.data.heroku.com

---

.github/workflows/tests.yaml

This repo was using one of the custom GitHub Actions runners when it did not need to (since it has no need of more compute, ARM CPUs or a static IP; public repos don't need a static IP for Git checkouts) - as proven by the fact that CI passes on this PR.
As such, it's been switched back to the standard GitHub Actions runners, as recommended here:
https://salesforce.quip.com/bu6UA0KImOxJ#temp:C:GZR57becb9df8d94f80b132168fd

Switch back to the public GitHub Actions runners

---

package.json
yarn.lock

[W-18241080](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002CRB3pYAH/view)
https://github.com/heroku/heroku-kafka-jsplugin/pull/232 unintentionally removed a needed dependency in `lodash.sortBy`. This adds it as an explicit dependency.

Add lodash sortby to deps
